// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
  //  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADjLYcWHKsp6x1fWQkCz-pH594fG9bYxw',
    appId: '1:182521028765:web:5e2797458ec1d693507474',
    messagingSenderId: '182521028765',
    projectId: 'masar-app-d3801',
    authDomain: 'masar-app-d3801.firebaseapp.com',
    storageBucket: 'masar-app-d3801.appspot.com',
    measurementId: 'G-9YCTZKJHSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-YXsQugum1E9BVwiKSsetWxqMYtDplz4',
    appId: '1:182521028765:android:0927835fdeab01ab507474',
    messagingSenderId: '182521028765',
    projectId: 'masar-app-d3801',
    storageBucket: 'masar-app-d3801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBog2z120SPiG92Grz9tk9CBfMeksBiERI',
    appId: '1:182521028765:ios:85af3bc448072a29507474',
    messagingSenderId: '182521028765',
    projectId: 'masar-app-d3801',
    storageBucket: 'masar-app-d3801.appspot.com',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBog2z120SPiG92Grz9tk9CBfMeksBiERI',
    appId: '1:182521028765:ios:85af3bc448072a29507474',
    messagingSenderId: '182521028765',
    projectId: 'masar-app-d3801',
    storageBucket: 'masar-app-d3801.appspot.com',
    iosBundleId: 'com.example.masarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADjLYcWHKsp6x1fWQkCz-pH594fG9bYxw',
    appId: '1:182521028765:web:6ae5f67c5cd0d6f1507474',
    messagingSenderId: '182521028765',
    projectId: 'masar-app-d3801',
    authDomain: 'masar-app-d3801.firebaseapp.com',
    storageBucket: 'masar-app-d3801.appspot.com',
    measurementId: 'G-ZC27QEHQJ7',
  );
}
*/